services:
  yapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yapi
    ports:
      - "4000:3000"
    depends_on:
      - mongo
    networks:
      - yapi_net

  mongo:
    image: bitnami/mongodb:latest
    container_name: yapi_mongo
    ports:
      - "27017:27017"
    volumes:
      - yapi_mongo_data:/bitnami/mongodb
    networks:
      - yapi_net

volumes:
  yapi_mongo_data:

networks:
  yapi_net:
    driver: bridge